from django.conf.urls import url
from . import views
urlpatterns = [
  url(r'^$'                            , views.index),
  url(r'^main/$'                       , views.main),
  url(r'^email/$'                      , views.email),
  url(r'^dashboard/$'                  , views.dashboard),
  url(r'^sessions/new$'                , views.login),
  url(r'^sessions/check/$'             , views.sessionsCheck),
  url(r'^accounts/login/$'             , views.login),
  url(r'^sessions/create$'             , views.sessions),
  url(r'^sessions/destroy$'            , views.destroy),
  url(r'^language/(?P<language>[\w\-]+)/$', views.language),
  url(r'^language/(?P<language>[\w\-]+)/(?P<location>[\w\-]+)/(?P<id>[\w\-]+)$', views.languageLocation),
  url(r'^about/$'                      , views.about),
  url(r'^about/update$'                , views.aboutUpdate),
  url(r'^services/$'                   , views.services),
  url(r'^services/new$'                , views.servicesNew),
  url(r'^services/add$'                , views.servicesAdd),
  url(r'^services/(?P<id>\d+)/edit$'   , views.servicesEdit),
  url(r'^services/(?P<id>\d+)/show$'   , views.servicesShow),
  url(r'^services/(?P<id>\d+)/update$' , views.servicesUpdate),
  url(r'^services/(?P<id>\d+)/destroy$', views.servicesDestroy),
  url(r'^projects/$'                   , views.projects),
  url(r'^projects/new$'                 , views.projectsNew),
  url(r'^projects/add$'                 , views.projectsAdd),
  url(r'^projects/(?P<id>\d+)/edit$'    , views.projectsEdit),
  url(r'^projects/(?P<id>\d+)/show$'    , views.projectsShow),
  url(r'^projects/(?P<id>\d+)/update$'  , views.projectsUpdate),
  url(r'^projects/(?P<id>\d+)/destroy$' , views.projectsDestroy),
  url(r'^clients/$'                    , views.clients),
  url(r'^clients/new$'                 , views.clientsNew),
  url(r'^clients/add$'                 , views.clientsAdd),
  url(r'^clients/(?P<id>\d+)/edit$'    , views.clientsEdit),
  url(r'^clients/(?P<id>\d+)/show$'    , views.clientsShow),
  url(r'^clients/(?P<id>\d+)/update$'  , views.clientsUpdate),
  url(r'^clients/(?P<id>\d+)/destroy$' , views.clientsDestroy),
  url(r'^contact/$'                    , views.contact),
  url(r'^contact/show$'                , views.contactShow),
  url(r'^contact/edit$'                , views.contactEdit),
  url(r'^contact/update$'               , views.contactUpdate),
  url(r'^contact/email$'               , views.contactEmail),
  url(r'^awards/$'                     , views.awards)

]