# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shortdesc', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=255)),
                ('phone2', models.CharField(max_length=255)),
                ('phone3', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('about_spanish', models.TextField(max_length=1000)),
                ('about_english', models.TextField(max_length=1000)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=255)),
                ('serviceNameS', models.CharField(max_length=255)),
                ('content1', models.TextField(max_length=1000)),
                ('content2', models.TextField(max_length=1000, null=True)),
                ('content3', models.TextField(max_length=1000, null=True)),
                ('content4', models.TextField(max_length=1000, null=True)),
                ('position', models.IntegerField(default=1)),
                ('linkstatus', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('imageSlider', models.CharField(max_length=255, null=True)),
                ('imageMenu', models.CharField(max_length=255, null=True)),
                ('imageDetails1', models.CharField(max_length=255, null=True)),
                ('imageDetails2', models.CharField(max_length=255, null=True)),
                ('imageDetails3', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(default='spanish', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='first_app.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('usertype', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
