# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nameShort', models.CharField(max_length=255)),
                ('nameLarge', models.CharField(max_length=255)),
                ('content1', models.TextField(max_length=5000)),
                ('content2', models.TextField(max_length=5000, null=True)),
                ('content3', models.TextField(max_length=5000, null=True)),
                ('content4', models.TextField(max_length=5000, null=True)),
                ('position', models.IntegerField(default=1)),
                ('linkstatus', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('imageSlider', models.CharField(max_length=255, null=True)),
                ('imageMenu', models.CharField(max_length=255, null=True)),
                ('imageDetails1', models.CharField(max_length=255, null=True)),
                ('imageDetails2', models.CharField(max_length=255, null=True)),
                ('imageDetails3', models.CharField(max_length=255, null=True)),
                ('website', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(default='spanish', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='first_app.Companies')),
            ],
        ),
    ]
