# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectsStatus', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('nameShort', models.CharField(max_length=255)),
                ('nameLarge', models.CharField(max_length=255)),
                ('descShort', models.TextField(max_length=255)),
                ('descLong', models.TextField(max_length=5000, null=True)),
                ('platform', models.TextField(max_length=5000, null=True)),
                ('technologies', models.TextField(max_length=5000, null=True)),
                ('content', models.TextField(max_length=5000, null=True)),
                ('position', models.IntegerField(default=1)),
                ('hours', models.IntegerField(default=1)),
                ('teamsize', models.IntegerField(default=1)),
                ('linkstatus', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=True)),
                ('imageSlider', models.CharField(max_length=255, null=True)),
                ('imageMenu', models.CharField(max_length=255, null=True)),
                ('imageDetails1', models.CharField(max_length=255, null=True)),
                ('imageDetails2', models.CharField(max_length=255, null=True)),
                ('imageDetails3', models.CharField(max_length=255, null=True)),
                ('website', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(default='spanish', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientprojects', to='first_app.Clients')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyprojects', to='first_app.Companies')),
            ],
        ),
    ]
